"use client";

import { useState } from "react";
import { useAssociateSensor, useContracts, useCreateContract, useEnergy, useSensor } from "@/features/sprint2/queries";
import { getErrorMessage } from "@/lib/api/errors";

const fieldClass = "h-10 rounded border border-slate-300 px-3";
export function MachineSprint2Panel({ machineId }: { machineId: number }) {
  const contracts = useContracts(machineId); const sensor = useSensor(machineId); const createContract = useCreateContract(machineId); const associate = useAssociateSensor(machineId);
  const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [totalCost, setTotalCost] = useState(""); const [hourlyRate, setHourlyRate] = useState(""); const [sensorId, setSensorId] = useState("");
  const [from, setFrom] = useState(new Date(Date.now() - 86400000).toISOString().slice(0, 16)); const [to, setTo] = useState(new Date().toISOString().slice(0, 16));
  const energy = useEnergy(machineId, new Date(from).toISOString(), new Date(to).toISOString());
  const activeContract = contracts.data?.find((item) => item.status === "VALID");
  return <div className="grid gap-6 lg:grid-cols-2">
    <section className="grid gap-4 rounded border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Contrato de alquiler</h2>{activeContract ? <dl className="grid gap-2 text-sm"><div><b>Estado:</b> {activeContract.status}</div><div><b>Periodo:</b> {activeContract.startDate.slice(0,10)} a {activeContract.endDate.slice(0,10)}</div><div><b>Costo:</b> S/ {activeContract.totalCost}</div><div><b>Tarifa:</b> S/ {activeContract.hourlyRate} / h</div></dl> : <form className="grid gap-3" onSubmit={(event) => { event.preventDefault(); createContract.mutate({ startDate, endDate, totalCost: Number(totalCost), hourlyRate: Number(hourlyRate) }); }}><input className={fieldClass} type="date" required value={startDate} onChange={(event) => setStartDate(event.target.value)} /><input className={fieldClass} type="date" required value={endDate} onChange={(event) => setEndDate(event.target.value)} /><input className={fieldClass} type="number" min="0" step="0.01" placeholder="Costo total" required value={totalCost} onChange={(event) => setTotalCost(event.target.value)} /><input className={fieldClass} type="number" min="0.01" step="0.01" placeholder="Tarifa por hora" required value={hourlyRate} onChange={(event) => setHourlyRate(event.target.value)} /><button className="h-10 rounded bg-workmeter-blue font-black text-white">Guardar contrato</button></form>}{createContract.isError ? <p className="text-sm font-bold text-red-700">{getErrorMessage(createContract.error)}</p> : null}</section>
    <section className="grid gap-4 rounded border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Sensor asociado</h2>{sensor.data ? <dl className="text-sm"><div><b>ID:</b> {sensor.data.identifier}</div><div><b>Tipo:</b> {sensor.data.type}</div><div><b>Estado:</b> {sensor.data.status}</div></dl> : <form className="flex gap-2" onSubmit={(event) => { event.preventDefault(); associate.mutate(sensorId); }}><input className={`${fieldClass} min-w-0 flex-1`} required placeholder="ID físico del sensor" value={sensorId} onChange={(event) => setSensorId(event.target.value)} /><button className="rounded bg-workmeter-blue px-4 font-black text-white">Asociar</button></form>}{associate.isError ? <p className="text-sm font-bold text-red-700">{getErrorMessage(associate.error)}</p> : null}</section>
    <section className="grid gap-4 lg:col-span-2"><h2 className="text-xl font-black">Consumo energético</h2><div className="flex flex-wrap gap-3"><input className={fieldClass} type="datetime-local" value={from} onChange={(event) => setFrom(event.target.value)} /><input className={fieldClass} type="datetime-local" value={to} onChange={(event) => setTo(event.target.value)} /></div>{energy.isLoading ? <p>Cargando consumo...</p> : null}{energy.isError ? <p className="font-bold text-red-700">{getErrorMessage(energy.error)}</p> : null}{energy.data?.readingCount === 0 ? <p className="text-workmeter-steel">No existen lecturas en el periodo seleccionado.</p> : null}{energy.data && energy.data.readingCount > 0 ? <div className="grid gap-3 sm:grid-cols-5">{[["Acumulado",energy.data.totalConsumption],["Promedio",energy.data.averageConsumption],["Mínimo",energy.data.minimumConsumption],["Máximo",energy.data.maximumConsumption],["Lecturas",energy.data.readingCount]].map(([label,value]) => <div key={label} className="rounded border bg-white p-4"><p className="text-xs font-bold text-workmeter-steel">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div> : null}</section>
  </div>;
}
