"use client";
import { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { PageHeader } from "@/components/ui/PageHeader";
import { Button } from "@/components/ui/Button";
import { useCurrentUser } from "@/features/auth/queries";
import { changePassword, updateProfile } from "@/lib/api/auth";
import { getErrorMessage } from "@/lib/api/errors";
export default function ProfilePage() { const user = useCurrentUser(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [current,setCurrent]=useState(""); const [next,setNext]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); async function saveProfile(){try{setError("");await updateProfile({name:name||undefined,email:email||undefined});setMessage("Perfil actualizado.");}catch(e){setError(getErrorMessage(e));}} async function savePassword(){if(next.length<8){setError("La nueva contraseña debe tener al menos 8 caracteres.");return;}try{setError("");await changePassword({currentPassword:current,newPassword:next});setCurrent("");setNext("");setMessage("Contraseña actualizada.");}catch(e){setError(getErrorMessage(e));}} return <AppShell><div className="grid gap-6"><PageHeader title="Perfil" description="Actualiza tus datos de acceso."/><section className="grid gap-4 rounded border bg-white p-6"><h2 className="text-lg font-black">Datos personales</h2><input className="h-11 rounded border px-3" placeholder={user.data?.name} value={name} onChange={e=>setName(e.target.value)}/><input className="h-11 rounded border px-3" placeholder={user.data?.email} value={email} onChange={e=>setEmail(e.target.value)}/><Button onClick={saveProfile}>Guardar perfil</Button></section><section className="grid gap-4 rounded border bg-white p-6"><h2 className="text-lg font-black">Cambiar contraseña</h2><input className="h-11 rounded border px-3" type="password" placeholder="Contraseña actual" value={current} onChange={e=>setCurrent(e.target.value)}/><input className="h-11 rounded border px-3" type="password" placeholder="Nueva contraseña" value={next} onChange={e=>setNext(e.target.value)}/><Button onClick={savePassword}>Cambiar contraseña</Button></section>{message&&<p className="font-bold text-emerald-700">{message}</p>}{error&&<p className="font-bold text-red-700">{error}</p>}</div></AppShell>; }
