import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { IncidentStatus, MachineStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AnalyticsQueryDto, IncidentQueryDto } from './dto';
import { IncidentPriorityService } from './incident-priority.service';
import { AuditLogService } from '../audit/audit-log.service';
import { AuditAction } from '@prisma/client';

@Injectable()
export class AnalyticsService {
  constructor(private readonly prisma: PrismaService, private readonly priority: IncidentPriorityService, private readonly audit: AuditLogService) {}
  private range(q: AnalyticsQueryDto) { const from = new Date(q.from); const to = new Date(q.to); if (!(from < to)) throw new BadRequestException('Analytics date range is invalid'); return { from, to }; }
  private async machineUsage(machineId: number, from: Date, to: Date) { const records = await this.prisma.machineStateRecord.findMany({ where: { machineId, startDate: { lt: to }, OR: [{ endDate: null }, { endDate: { gt: from } }] } }); let active=0,inactive=0; for(const r of records){ const start=Math.max(r.startDate.getTime(),from.getTime()); const end=Math.min((r.endDate??to).getTime(),to.getTime()); const h=Math.max(0,(end-start)/3600000); if(r.status===MachineStatus.ACTIVE)active+=h; if(r.status===MachineStatus.INACTIVE)inactive+=h; } return { activeHours:active, inactiveHours:inactive, totalHours:active+inactive }; }
  async comparison(q: AnalyticsQueryDto) { const {from,to}=this.range(q); const ids=(q.machineIds??'').split(',').map(Number).filter(Number.isInteger); if(ids.length<2) throw new BadRequestException('At least two machines are required'); const machines=await this.prisma.machine.findMany({where:{id:{in:ids},siteId:q.siteId?Number(q.siteId):undefined},include:{site:true}}); if(machines.length<2) throw new BadRequestException('At least two existing machines are required'); const rows=await Promise.all(machines.map(async m=>{const u=await this.machineUsage(m.id,from,to);const [energy,alerts,incidents,maintenance]=await Promise.all([this.prisma.sensorReading.aggregate({where:{machineId:m.id,timestamp:{gte:from,lt:to}},_sum:{energyConsumption:true}}),this.prisma.alert.count({where:{machineId:m.id,generationDate:{gte:from,lt:to}}}),this.prisma.operationalIncident.count({where:{machineId:m.id,registrationDate:{gte:from,lt:to}}}),this.prisma.maintenanceRecord.count({where:{machineId:m.id,maintenanceDate:{gte:from,lt:to}}})]);return {machineId:m.id,machineCode:m.code,machineType:m.type,siteId:m.siteId,siteName:m.site.name,...u,effectiveUsagePercentage:u.totalHours?u.activeHours/u.totalHours*100:null,energyConsumption:Number(energy._sum.energyConsumption??0),inactivityCost:u.inactiveHours*Number(m.hourlyRate),alertCount:alerts,incidentCount:incidents,maintenanceCount:maintenance,currentStatus:m.currentStatus,hasData:u.totalHours>0};})); return {from:q.from,to:q.to,timeZone:process.env.WORK_TIMEZONE??'America/Lima',machines:rows}; }
  async trends(q: AnalyticsQueryDto) { const {from,to}=this.range(q); const ids=q.machineId? [Number(q.machineId)] : undefined; const machines=await this.prisma.machine.findMany({where:{id:ids?{in:ids}:undefined,siteId:q.siteId?Number(q.siteId):undefined}}); const buckets: { period:string; activeHours:number; inactiveHours:number; energyConsumption:number; inactivityCost:number; hasData:boolean }[]=[]; const step=q.groupBy==='weekly'?7:1; for(let cursor=new Date(from);cursor<to;cursor.setUTCDate(cursor.getUTCDate()+step)){const start=new Date(cursor),end=new Date(cursor);end.setUTCDate(end.getUTCDate()+step);const actualEnd=end<to?end:to;let a=0,i=0,e=0,c=0;for(const m of machines){const u=await this.machineUsage(m.id,start,actualEnd);a+=u.activeHours;i+=u.inactiveHours;c+=u.inactiveHours*Number(m.hourlyRate);const en=await this.prisma.sensorReading.aggregate({where:{machineId:m.id,timestamp:{gte:start,lt:actualEnd}},_sum:{energyConsumption:true}});e+=Number(en._sum.energyConsumption??0);}buckets.push({period:start.toISOString().slice(0,10),activeHours:Number(a.toFixed(2)),inactiveHours:Number(i.toFixed(2)),effectiveUsagePercentage:(a+i)?Number((a/(a+i)*100).toFixed(2)):null,energyConsumption:Number(e.toFixed(2)),inactivityCost:Number(c.toFixed(2)),hasData:a+i>0} as typeof buckets[number]);}return {from:q.from,to:q.to,groupBy:q.groupBy,timeZone:process.env.WORK_TIMEZONE??'America/Lima',data:buckets}; }
  prioritized(q: IncidentQueryDto) { return this.priority.prioritize({severity:q.severity as never,status:q.status as never,machineId:q.machineId?Number(q.machineId):undefined,siteId:q.siteId?Number(q.siteId):undefined}); }
  async updateIncident(id:number,userId:number,status:IncidentStatus){const old=await this.prisma.operationalIncident.findUnique({where:{id}});if(!old)throw new NotFoundException('Incident not found');const updated=await this.prisma.operationalIncident.update({where:{id},data:{status}});await this.audit.record({userId,action:AuditAction.INCIDENT_STATUS_CHANGED,resource:'OperationalIncident',resourceId:id,metadata:{from:old.status,to:status}});return updated;}
}
