"use client";

import { useParams } from "next/navigation";
import { useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { useAlert } from "@/features/alerts/queries";
import { useCreateIncident, useIncidents } from "@/features/sprint2/queries";
import { formatDateTime } from "@/lib/utils";
import { getErrorMessage } from "@/lib/api/errors";

export default function AlertDetailPage() {
  const alertId = Number(useParams<{ id: string }>().id); const alert = useAlert(alertId, alertId > 0); const incidents = useIncidents(alertId); const create = useCreateIncident(alertId);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [severity, setSeverity] = useState("MEDIUM");
  return <AppShell><div className="grid gap-6"><h1 className="text-3xl font-black">Detalle de alerta</h1>{alert.isLoading ? <p>Cargando alerta...</p> : null}{alert.data ? <section className="grid gap-2 rounded border bg-white p-5 text-sm"><p><b>Máquina:</b> {alert.data.machine.code}</p><p><b>Obra:</b> {alert.data.machine.site.name}</p><p><b>Prioridad:</b> {alert.data.priority === "HIGH" ? "Prioridad alta" : alert.data.priority}</p><p><b>Estado:</b> {alert.data.status}</p><p><b>Generada:</b> {formatDateTime(alert.data.generationDate)}</p><p><b>Inicio de inactividad:</b> {formatDateTime(alert.data.inactiveSince)}</p><p><b>Duración:</b> {Math.round(alert.data.inactiveDurationMinutes)} min</p>{alert.data.resolvedDate ? <p><b>Resuelta:</b> {formatDateTime(alert.data.resolvedDate)}</p> : null}</section> : null}<section className="grid gap-4"><h2 className="text-xl font-black">Registrar incidencia</h2><form className="grid gap-3 rounded border bg-white p-5" onSubmit={(event) => { event.preventDefault(); create.mutate({ title, description, severity }, { onSuccess: () => { setTitle(""); setDescription(""); } }); }}><input className="h-10 rounded border px-3" required placeholder="Título o tipo" value={title} onChange={(event) => setTitle(event.target.value)} /><textarea className="min-h-28 rounded border p-3" required placeholder="Descripción" value={description} onChange={(event) => setDescription(event.target.value)} /><select className="h-10 rounded border px-3" value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option><option value="CRITICAL">Crítica</option></select><button className="h-10 rounded bg-workmeter-blue font-black text-white">Guardar incidencia</button>{create.isError ? <p className="font-bold text-red-700">{getErrorMessage(create.error)}</p> : null}</form></section><section className="grid gap-3"><h2 className="text-xl font-black">Historial de incidencias</h2>{incidents.data?.length === 0 ? <p>No hay incidencias registradas.</p> : null}{incidents.data?.map((incident) => <article key={incident.id} className="rounded border bg-white p-4"><div className="flex justify-between"><h3 className="font-black">{incident.title}</h3><span className="font-bold">{incident.severity}</span></div><p className="mt-2 text-sm">{incident.description}</p><p className="mt-2 text-xs text-workmeter-steel">{incident.registeredBy.name} · {formatDateTime(incident.registrationDate)}</p></article>)}</section></div></AppShell>;
}
