@startuml "Class: Realization"
interface PriorizadorIncidencias {
  + priorizar()
}

class PriorizadorPorInactividad implements PriorizadorIncidencias {
  + priorizar()
}

class PriorizadorPorCosto implements PriorizadorIncidencias {
  + priorizar()
}
@enduml
