@startuml "Business Use Case: Evaluar continuidad y optimizar costos"
left to right direction

actor/ "Administrador de\nProyectos" <<Business Worker>> as Admin
actor/ "Direccion de la\nConstructora" <<Business Actor>> as Direccion

usecase/ "Evaluar continuidad\ndel alquiler y optimizar costos" as BUC5

Admin --> BUC5
Direccion --> BUC5

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}
@enduml
